// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list_reports.ts
import { createClient } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(globalThis.process.env.SUPABASE_URL, globalThis.process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_reports_default = defineTool({
  name: "list_reports",
  title: "List health reports",
  description: "List the signed-in user's uploaded health reports (blood work / lab reports), most recent first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("Max reports to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("reports").select("id, original_filename, file_name, report_date, report_type, extraction_status, is_baseline, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { reports: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list_markers.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(globalThis.process.env.SUPABASE_URL, globalThis.process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_markers_default = defineTool2({
  name: "list_markers",
  title: "List extracted health markers",
  description: "List biomarkers extracted from the signed-in user's reports. Optionally filter by marker name (case-insensitive substring) or report id.",
  inputSchema: {
    marker_name: z2.string().optional().describe("Optional case-insensitive substring to match marker name (e.g. 'vitamin d', 'ldl')."),
    report_id: z2.string().uuid().optional().describe("Optional report id to restrict results to a single report."),
    limit: z2.number().int().min(1).max(200).default(100)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ marker_name, report_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser2(ctx).from("extracted_markers").select("id, marker_name, value, unit, reference_range, report_date, report_id").eq("user_id", ctx.getUserId()).order("report_date", { ascending: false }).limit(limit);
    if (marker_name) q = q.ilike("marker_name", `%${marker_name}%`);
    if (report_id) q = q.eq("report_id", report_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { markers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get_latest_insights.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser3(ctx) {
  return createClient3(globalThis.process.env.SUPABASE_URL, globalThis.process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_latest_insights_default = defineTool3({
  name: "get_latest_insights",
  title: "Get latest health insights",
  description: "Get the signed-in user's most recent Chirayu AI health insight analysis (summary, markers, recommendations, and 3-month plan).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("health_insights").select("id, analysis_data, report_ids, version, created_at, last_updated_at, last_updated_sections, is_invalidated").eq("user_id", ctx.getUserId()).is("superseded_by", null).order("created_at", { ascending: false }).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No insights available yet. Upload a health report to generate insights." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { insight: data }
    };
  }
});

// src/lib/mcp/tools/get_profile.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser4(ctx) {
  return createClient4(globalThis.process.env.SUPABASE_URL, globalThis.process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_profile_default = defineTool4({
  name: "get_profile",
  title: "Get user profile and questionnaire",
  description: "Get the signed-in user's profile and most recent lifestyle/health questionnaire responses.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    const userId = ctx.getUserId();
    const [{ data: profile, error: pErr }, { data: q, error: qErr }] = await Promise.all([
      sb.from("profiles").select("id, full_name, phone, created_at").eq("id", userId).maybeSingle(),
      sb.from("questionnaire_responses").select("*").eq("user_id", userId).order("updated_at", { ascending: false }).limit(1).maybeSingle()
    ]);
    if (pErr) return { content: [{ type: "text", text: pErr.message }], isError: true };
    if (qErr) return { content: [{ type: "text", text: qErr.message }], isError: true };
    const payload = { profile, questionnaire: q };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jxsgahftvwhlhvcovoxi";
var mcp_default = defineMcp({
  name: "chirayu-ai-mcp",
  title: "Chirayu AI",
  version: "0.1.0",
  instructions: "Read-only access to the signed-in Chirayu AI user's health data: uploaded reports, extracted biomarkers, latest AI-generated insights, and profile/questionnaire. Use these tools to answer questions about the user's own health trends and lab results.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_reports_default, list_markers_default, get_latest_insights_default, get_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
